### ISSUE TITLE
Absolute numbering > 100 breaks correct season assignment

### ISSUE THREAD

**Issue by StillLoading** [jellyfin/jellyfin-plugin-anime#17]
Shows with more than 100 episodes get incorrectly recognised when using absolute numbers for episode names e.g. One Piece - 001.mkv or One Piece - 100.mkv results in the creation of a "Specials" season and episodes get shuffled between all available seasons.

I know that Anime has a rather niche user base and this issue probably has an even smaller impact since most of those users have adopted the tvdb naming scheme. But there are some who still use the standard AniDB naming scheme and they will encounter this problem eventually. 

A fix could be an extra library content type that does not rely on season (since animes don't have season like TV shows do).
Or simply putting all episodes into season 1 by default.

**Comment by Matt07211** [comment]
I currently don't have an series on my local hard drives that hits triple digits yet (Had to clear space), can you please try changing the airing order to absolute ordering on the series and report the results?

**Comment by hawken93** [comment]
I grepped my library to find some examples

One Piece
Fairy Tail
_Probably_ Naruto
Kateikyoushi Hitman REBORN!
Legend of the Galactic Heroes
Inuyasha

**Comment by StillLoading** [comment]
> I currently don't have an series on my local hard drives that hits triple digits yet (Had to clear space), can you please try changing the airing order to absolute ordering on the series and report the results?

I tried this with my local test installation and it worked with the show I tested. I tested with "Hunter x Hunter (2011)" which has 148 episodes in total. After changing the display order to absolute and a bit of waiting (looks like it did a full metadata rescan) it did indeed split into 3 seasons and the episodes seem to match.

I noticed 2 things while testing.

1. All of my shows are 0 padded (e.g. episode 1 is 01 or 001) which is fine, as far as I can tell, until it hits 3 digits then a Specials season appears. I removed the padding for the test show and that fixed it.
2. For display order absolute to work TheTVDB episode metadata downloader has to be active. It looks like AniDB can be activated but doesn't actually do anything. At least there's no "External Id" for AniDB in the episode metadata.

I'm currently testing One Piece (869 episodes in my library) to check if what I found out so far still holds up with even bigger shows. But it will probably take a while before I can report my findings.

**Comment by Matt07211** [comment]
I've already Created an issue to set the entire library  at once to a different airing order, https://github.com/jellyfin/jellyfin/issues/697

But I'll admit, after looking at the plugin, I'm surprised it's working as well as it did.....

And as for the tvdb point, looks like anidb has a anidb to tvdb mapper for people who like to use the SxxExx format for TV shows.

**Comment by StillLoading** [comment]
So, the One Piece rescan is finally done and except for a few episodes with numbers in their title it worked.

I don't now if this issue should be closed or not since there are a lot of prerequisites for this to actually work. 
I think it would be preferable if anime shows would be displayed as **Show->Episode** rather than **Show->Season->Episode**.

**Comment by Matt07211** [comment]
Yes, please do leave the issue open, this plugin is going to take a lot of work to get it to a satisfactory level.

And the points you raised are valid ones that annoy me to, which that should be worked on

**Comment by hawken93** [comment]
If show->ep is going to be the future I'd like to have collections to organize things :)

**Comment by hawken93** [comment]
And I'd like to keep specials folder stuff though

**Comment by Matt07211** [comment]
What do you mean by "Collections"? Lumping related series together?

**Comment by hawken93** [comment]
Well, yes

**Comment by hawken93** [comment]
It's supposed to exist for movies so you could for instance group all of Harry Potter or Star Wars

**Comment by Matt07211** [comment]
https://github.com/jellyfin/jellyfin/issues/1180

Posting this here for reference for when ever I do get around to attempting anything

**Comment by Matt07211** [comment]
https://github.com/jellyfin/jellyfin/issues/1180

Posting this here for reference for when ever I do get around to attempting anything

**Comment by dkanada** [comment]
Should be resolved in the next update.

**Comment by Matt07211** [comment]
> Should be resolved in the next update.

Next jellyfin update or plugin update? I think it's about time I give it a go!

**Comment by Matt07211** [comment]
This has not been resolved, I just tested with fairly tail which is 175 eps long, The first 99 Eps get recognised as specials, and the remain get recognised as season 1

**Comment by ficarra1002** [comment]
> Should be resolved in the next update.

Can confirm what @Matt07211 said, this is still an issue. I have an anime series that uses absolute numbering and 101 is detected as episode 1, and so on.
